# Bash profile

if [[ -f "${HOME}/.bashrc" ]]; then
    . ~/.bashrc
fi

# vim:ft=sh

#[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
