# Nothing here all stuff is in ~/.bash.d
# source file in that directory instead

if [[ -d "${HOME}/.bash.d" ]]; then
    for rc in ${HOME}/.bash.d/*.sh; do
        source $rc;
    done
    unset rc
fi

#export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
