---
- name: 'Setup .vim directory'
  file:
    path: "{{ lookup('env', 'HOME') }}/.vim/{{ item }}"
    owner: "{{ lookup('env', 'USER') }}"
    mode: '0755'
    state: directory
  with_items:
    - autoload
    - bundle

- name: 'Install pathogen'
  get_url:
    url: 'https://tpo.pe/pathogen.vim'
    dest: "{{ lookup('env', 'HOME') }}/.vim/autoload/pathogen.vim"
    mode: '0644'

- name: 'Install vimrc'
  copy:
    src: 'vimrc'
    dest: "{{ lookup('env', 'HOME') }}/.vimrc"
    owner: "{{ lookup('env', 'USER') }}"
    mode: '0644'

- name: 'Install vim-go syntax file'
  git:
    repo: 'https://github.com/fatih/vim-go.git'
    dest: "{{ lookup('env', 'HOME') }}/.vim/bundle/vim-go"

- name: 'Install vim-sensible'
  git:
    repo: 'https://tpope.io/vim/sensible.git'
    dest: "{{ lookup('env', 'HOME') }}/.vim/bundle/sensible"
- name: 'Install vim-syntastic'
  git:
    repo: 'https://github.com/scrooloose/syntastic.git'
    dest: "{{ lookup('env', 'HOME') }}/.vim/bundle/syntastic"

- name: 'Install vim-ansible-yaml'
  git:
    repo: 'https://github.com/pearofducks/ansible-vim.git'
    dest: "{{ lookup('env', 'HOME') }}/.vim/bundle/ansible-vim"

- name: 'Install vim-json'
  git:
    repo: 'https://github.com/elzr/vim-json.git'
    dest: "{{ lookup('env', 'HOME') }}/.vim/bundle/vim-json"

- name: 'Install vim-terraform'
  git:
    repo: 'https://github.com/hashivim/vim-terraform.git'
    dest: "{{ lookup('env', 'HOME') }}/.vim/bundle/vim-terraform"

- name: 'Install vim-dockerfile'
  git:
    repo: 'https://github.com/ekalinin/Dockerfile.vim.git'
    dest: "{{ lookup('env', 'HOME') }}/.vim/bundle/Dockerfile"

- name: 'Install vim-puppet'
  git:
    repo: 'https://github.com/rodjek/vim-puppet.git'
    dest: "{{ lookup('env', 'HOME') }}/.vim/bundle/vim-puppet"

- name: 'Install tabular'
  git:
    repo: "https://github.com/godlygeek/tabular"
    dest: "{{ lookup('env', 'HOME') }}/.vim/bundle/tabular"

- name: 'Install vim-toml'
  git:
    repo: "https://github.com/cespare/vim-toml.git"
    dest: "{{ lookup('env', 'HOME') }}/.vim/bundle/vim-toml"

- name: 'Install vim-better-whitespace'
  git:
    repo: "https://github.com/ntpeters/vim-better-whitespace.git"
    dest: "{{ lookup('env', 'HOME') }}/.vim/bundle/vim-better-whitespace"
